--
-- Script was generated by Devart dbForge Studio 2022 for MySQL, Version 9.1.21.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 1/16/2024 7:38:49 PM
-- Server version: 10.4.27
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO freecvcreator.user(ID, EmailAddress, Password, UserIsAdmin, PublicProfileLinkActive, DataSaveActive) VALUES
('7qT4c6r1', 'nagy.istvan@domain.hu', 'admin', 0, 1, 1);

INSERT INTO freecvcreator.personaldetails(PDID, FirstName, LastName, Address, PhoneNumber, ProfileImageExists, ProfileImageTitle, ProfileImagePath) VALUES
('7qT4c6r1', 'István', 'Nagy', '1212 Budapest, Béke tér 1.', '+36 30 000 0000', 1, 'example-cv-image.jpg', '../../06-temp/7qT4c6r1/example-cv-image.jpg');

INSERT INTO freecvcreator.educationandqualifications(EAQID, StartOfStudy, EndOfStudy, InstitutionName, Qualification, Studies) VALUES
('7qT4c6r1', '1999-01-01', '2000-01-01', 'Budapesti Képzési Központ', 'Webfejlesztő', 'HTML, CSS, Bootstrap, PHP, MySQL, MSSQL, Git, Unit testing');

INSERT INTO freecvcreator.workexperience(WEID, StartOfEmployment, EndOfEmployment, WorkplaceName, Position, JobDescription) VALUES
('7qT4c6r1', '2002-01-01', '0000-00-00', 'Budapesti Műszaki Egyetem', 'Informatikus', 'Helyszíni informatikai támogatói feladatok ellátása (hibaelhárítás, üzembe helyezés, költöztetés, telepítés, stb.). A felmerülő problémák megoldása, vagy hatáskör hiányában továbbítása a megfelelő szakembereknek, illetve a vezetés felé. Kapcsolattartás az ügyfelekkel, vezetőkkel, a támogatásban részt vevő külső szolgáltatókkal. A feladatokhoz kapcsolódó adminisztrációs munkák elvégzése.');

INSERT INTO freecvcreator.languages(LID, Language, Level) VALUES
('7qT4c6r1', 'Angol', 'B2 - Középfok');

INSERT INTO freecvcreator.skills(SID, Skills) VALUES
('7qT4c6r1', 'Microsoft Office csomag haladó szintű ismerete.');