--
-- Script was generated by Devart dbForge Studio 2022 for MySQL, Version 9.1.21.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 1/16/2024 5:37:59 PM
-- Server version: 10.4.27
-- Client version: 4.1
--


-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

CREATE DATABASE freecvcreator
	CHARACTER SET utf8mb4
	COLLATE utf8mb4_general_ci;

--
-- Set default database
--
USE freecvcreator;

--
-- Create table `user`
--
CREATE TABLE user (
  ID VARCHAR(8) NOT NULL,
  EmailAddress VARCHAR(255) NOT NULL,
  Password VARCHAR(255) NOT NULL,
  UserIsAdmin TINYINT(1) DEFAULT 0,
  PublicProfileLinkActive TINYINT(1) DEFAULT 0,
  DataSaveActive TINYINT(1) DEFAULT 1,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create index `EmailAddress` on table `user`
--
ALTER TABLE user 
  ADD UNIQUE INDEX EmailAddress(EmailAddress);

--
-- Create table `personaldetails`
--
CREATE TABLE personaldetails (
  PDID VARCHAR(8) NOT NULL,
  FirstName VARCHAR(255) NOT NULL,
  LastName VARCHAR(255) NOT NULL,
  Address VARCHAR(255) DEFAULT NULL,
  PhoneNumber VARCHAR(255) DEFAULT NULL,
  ProfileImageExists TINYINT(1) DEFAULT 0,
  ProfileImageTitle VARCHAR(255) DEFAULT NULL,
  ProfileImagePath VARCHAR(255) DEFAULT NULL
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create foreign key
--
ALTER TABLE personaldetails 
  ADD CONSTRAINT personaldetails_ibfk_1 FOREIGN KEY (PDID)
    REFERENCES user(ID) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Create table `educationandqualifications`
--
CREATE TABLE educationandqualifications (
  EAQID VARCHAR(8) NOT NULL,
  StartOfStudy DATE NOT NULL,
  EndOfStudy DATE DEFAULT NULL,
  InstitutionName VARCHAR(255) NOT NULL,
  Qualification VARCHAR(255) NOT NULL,
  Studies VARCHAR(1000) DEFAULT NULL
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 4096,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create foreign key
--
ALTER TABLE educationandqualifications 
  ADD CONSTRAINT educationandqualifications_ibfk_1 FOREIGN KEY (EAQID)
    REFERENCES user(ID) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Create table `workexperience`
--
CREATE TABLE workexperience (
  WEID VARCHAR(8) NOT NULL,
  StartOfEmployment DATE NOT NULL,
  EndOfEmployment DATE DEFAULT NULL,
  WorkplaceName VARCHAR(255) NOT NULL,
  Position VARCHAR(255) NOT NULL,
  JobDescription VARCHAR(1000) DEFAULT NULL
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create foreign key
--
ALTER TABLE workexperience 
  ADD CONSTRAINT workexperience_ibfk_1 FOREIGN KEY (WEID)
    REFERENCES user(ID) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Create table `languages`
--
CREATE TABLE languages (
  LID VARCHAR(8) NOT NULL,
  Language VARCHAR(255) DEFAULT NULL,
  Level VARCHAR(255) DEFAULT NULL
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create foreign key
--
ALTER TABLE languages 
  ADD CONSTRAINT languages_ibfk_1 FOREIGN KEY (LID)
    REFERENCES user(ID) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Create table `skills`
--
CREATE TABLE skills (
  SID VARCHAR(8) NOT NULL,
  Skills VARCHAR(1000) DEFAULT NULL
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create foreign key
--
ALTER TABLE skills 
  ADD CONSTRAINT skills_ibfk_1 FOREIGN KEY (SID)
    REFERENCES user(ID) ON DELETE CASCADE ON UPDATE CASCADE;

/*
SELECT * FROM user;
SELECT * FROM personaldetails;
SELECT * FROM educationandqualifications;
SELECT * FROM workexperience;
SELECT * FROM languages;
SELECT * FROM skills;
*/